name: admin_x_technician_panel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # PDF creation
  pdf: ^3.10.7
  printing: ^5.11.1

  # File storage
  path_provider: ^2.1.3

  firebase_core: ^2.24.0

  # Firebase Authentication
  firebase_auth: ^4.17.3

  # Cloud Firestore Database
  cloud_firestore: ^4.13.3

  # Firebase Storage for files
  firebase_storage: ^11.5.3

  # Firebase Cloud Messaging (Push Notifications)
  firebase_messaging: ^14.7.3

  # Firebase Analytics
  firebase_analytics: ^10.8.3

  # Firebase Crashlytics
  firebase_crashlytics: ^3.2.3



  # File opener
  open_filex: ^4.7.0

  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # HTTP / API
  http: ^1.2.1

  # State management
  provider: ^6.1.2

  # Local storage
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
dev_dependencies:
  fake_cloud_firestore: ^2.5.2
  network_image_mock: ^2.1.1
    # Or if you want to specify individual files:
    # - assets/images/logo.png
    # - assets/images/icon.png