// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj54vPr_ZuOmpXeIhqt1PcqK8vjoYuhs',
    appId: '1:842549323174:android:d89aa04e5a081514235b67',
    messagingSenderId: '842549323174',
    projectId: 'handyman-ff7d0',
    storageBucket: 'handyman-ff7d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN-DBKvdnkZpnc_3dEA-b91Buap8xp87c',
    appId: '1:842549323174:ios:ad0df851f5c4a3af235b67',
    messagingSenderId: '842549323174',
    projectId: 'handyman-ff7d0',
    storageBucket: 'handyman-ff7d0.firebasestorage.app',
    iosBundleId: 'com.example.adminXTechnicianPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN-DBKvdnkZpnc_3dEA-b91Buap8xp87c',
    appId: '1:842549323174:ios:ad0df851f5c4a3af235b67',
    messagingSenderId: '842549323174',
    projectId: 'handyman-ff7d0',
    storageBucket: 'handyman-ff7d0.firebasestorage.app',
    iosBundleId: 'com.example.adminXTechnicianPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOKYTVpTod8FTwQltrM25NCrVNBIuZvwk',
    appId: '1:842549323174:web:7b0c73592be41be3235b67',
    messagingSenderId: '842549323174',
    projectId: 'handyman-ff7d0',
    authDomain: 'handyman-ff7d0.firebaseapp.com',
    storageBucket: 'handyman-ff7d0.firebasestorage.app',
    measurementId: 'G-FJNM3RZHS1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKYTVpTod8FTwQltrM25NCrVNBIuZvwk',
    appId: '1:842549323174:web:7b0c73592be41be3235b67',
    messagingSenderId: '842549323174',
    projectId: 'handyman-ff7d0',
    authDomain: 'handyman-ff7d0.firebaseapp.com',
    storageBucket: 'handyman-ff7d0.firebasestorage.app',
    measurementId: 'G-FJNM3RZHS1',
  );

}