// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mwhsBRlQZkZ7m7MZGl3FLgeaX8KX1Ig',
    appId: '1:1077866533312:android:b280b6e277458bd1b77825',
    messagingSenderId: '1077866533312',
    projectId: 'handyman-3308d',
    storageBucket: 'handyman-3308d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1nFOXBXlj7otMHIyJILROk0BDAeiFYH4',
    appId: '1:1077866533312:ios:78670e7776dac001b77825',
    messagingSenderId: '1077866533312',
    projectId: 'handyman-3308d',
    storageBucket: 'handyman-3308d.firebasestorage.app',
    iosBundleId: 'com.handyman.adminworker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1nFOXBXlj7otMHIyJILROk0BDAeiFYH4',
    appId: '1:1077866533312:ios:78670e7776dac001b77825',
    messagingSenderId: '1077866533312',
    projectId: 'handyman-3308d',
    storageBucket: 'handyman-3308d.firebasestorage.app',
    iosBundleId: 'com.handyman.adminworker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5JavEkv7pZyb2iOk7-HO3KyfA4qVQ-zU',
    appId: '1:1077866533312:web:91d4b2e053547a22b77825',
    messagingSenderId: '1077866533312',
    projectId: 'handyman-3308d',
    authDomain: 'handyman-3308d.firebaseapp.com',
    storageBucket: 'handyman-3308d.firebasestorage.app',
    measurementId: 'G-LV4BG9GFRS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5JavEkv7pZyb2iOk7-HO3KyfA4qVQ-zU',
    appId: '1:1077866533312:web:91d4b2e053547a22b77825',
    messagingSenderId: '1077866533312',
    projectId: 'handyman-3308d',
    authDomain: 'handyman-3308d.firebaseapp.com',
    storageBucket: 'handyman-3308d.firebasestorage.app',
    measurementId: 'G-LV4BG9GFRS',
  );
}
